version: "3"
services: 
  frontend:
    container_name: frontend
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    volumes:
      - ./../../.:/app
    ports:
      - 3001:3000
    env_file:
      - ../../.env
